#!/bin/sh

[ "$ACTION" = ifup ] || exit 0
pidof mcpd >/dev/null || exit 0

IFNAME=$(uci -q get network.$INTERFACE.ifname)

[ "${IFNAME:0:1}" == "@" ] && exit 0

. /lib/functions/network.sh && network_get_device dev $INTERFACE

RELOAD=0
uci -q get mcpd.mcpd.igmp_snooping_interfaces | grep -wq "$dev" && RELOAD=1
uci -q get mcpd.mcpd.igmp_proxy_interfaces | grep -wq "$INTERFACE" && RELOAD=1

[ $RELOAD -eq 1 ] || exit 0

/etc/init.d/mcpd enabled && /etc/init.d/mcpd reload

